### ISSUE TITLE
Possible updates to Readme

### ISSUE THREAD

**Issue by lebsral** [flauc/angular2-easy-forms#4]
@flauc ,

With the upgrade to 2.0.  I think we need to upgrade the ReadMe to remove
You also need to declare the library in your system.js config. 

``` js
var map = { 'angular2-easy-forms': 'node_modules/angular2-easy-forms' },
var packages = { 'angular2-easy-forms': {main: 'components.js', defaultExtension: 'js'} }
```

and then change

``` typescript
//...
import {EasyFormsModule} from '/angular2-easy-forms';

import
@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        EasyFormsModule
    ],
    providers: [],
    declarations: [AppComponent],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

Am I missing anything?

**Comment by flauc** [comment]
Are you using webpack or system.js? If you're using system.js i think you still need to add the map and packages variables in to your config.

**Comment by lebsral** [comment]
I'm using webpack now.

**Comment by flauc** [comment]
Yes that's why you don't need to map the library. I should add the `For system.js` subtitle before that line.
